name: Build Kivy Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y openjdk-17-jdk zip unzip

    - name: Install Buildozer
      run: |
        pip install buildozer cython

    - name: Build APK
      env:
        BUILDOZER_ALLOW_ROOT: "1"
        CI: "true"
      run: python3 run_buildozer.py

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: bin/*.apk
